/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.emuladordeemprestimos;

//import Backup.*;
import Dao.EmprestimoDAO;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Formatador;
import model.SimuladorEmprestimos;

/**
 *
 * @author berna
 */
public class PainelEmuladorDeEmprestimos extends javax.swing.JPanel {

    /**
     * Creates new form PainelAmortizacoes
     */
    public PainelEmuladorDeEmprestimos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tfCapital = new javax.swing.JTextField();
        tfTaxaJuros = new javax.swing.JTextField();
        spinnerParcelas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSimular = new javax.swing.JButton();
        lbDivida = new javax.swing.JLabel();
        lbDetalhes = new javax.swing.JLabel();
        lbParcelas = new javax.swing.JLabel();
        lbCusto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbTaxaJuros = new javax.swing.JLabel();
        lbValorParcelas = new javax.swing.JLabel();
        lbJuros = new javax.swing.JLabel();
        btnAderir = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(950, 594));
        setMinimumSize(new java.awt.Dimension(950, 594));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(950, 594));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfCapital.setDocument(new Formatador(9, Formatador.TipoEntrada.NUMERO_DECIMAL));
        tfCapital.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCapital.setText("0");
        jPanel1.add(tfCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 184, -1));

        tfTaxaJuros.setDocument(new Formatador(4, Formatador.TipoEntrada.NUMERO_DECIMAL));
        tfTaxaJuros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tfTaxaJuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 144, -1));

        spinnerParcelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(spinnerParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 122, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Valor de Empréstimo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Número de Parcelas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Taxa de Juros");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        btnSimular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimular.setText("Simular");
        btnSimular.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnSimularMouseDragged(evt);
            }
        });
        btnSimular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSimularFocusGained(evt);
            }
        });
        btnSimular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimularMouseEntered(evt);
            }
        });
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimular, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        lbDivida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDivida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Icones emprestimo/Total a Pagar.png"))); // NOI18N
        lbDivida.setText("Valor Total a pagar:");
        jPanel1.add(lbDivida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        lbDetalhes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDetalhes.setText("Detalhes:");
        jPanel1.add(lbDetalhes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        lbParcelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbParcelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Icones emprestimo/icons8-slice-50.png"))); // NOI18N
        lbParcelas.setText("Número de Parcelas:");
        jPanel1.add(lbParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        lbCusto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Icones emprestimo/Custo do Emprestimo.png"))); // NOI18N
        lbCusto.setText("Custo do Emprestimo:");
        jPanel1.add(lbCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 261, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 610, 261, 10));

        lbTaxaJuros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTaxaJuros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Icones Gastos/icons8-priority-50.png"))); // NOI18N
        lbTaxaJuros.setText("Taxa de Juros:");
        jPanel1.add(lbTaxaJuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        lbValorParcelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbValorParcelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Icones emprestimo/Valor das Parcelas (2).png"))); // NOI18N
        lbValorParcelas.setText("Valor das Parcelas:");
        jPanel1.add(lbValorParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        lbJuros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbJuros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Icones Gastos/icons8-spend-50.png"))); // NOI18N
        lbJuros.setText("Valor Total em Juros:");
        jPanel1.add(lbJuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        btnAderir.setText("Aderir");
        btnAderir.setEnabled(false);
        btnAderir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAderirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAderir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 80, 30));

        jTabbedPane1.addTab("Simulador", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSimularFocusGained

    }//GEN-LAST:event_btnSimularFocusGained

    private void btnSimularMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularMouseDragged

    }//GEN-LAST:event_btnSimularMouseDragged

    private void btnSimularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularMouseEntered

        validar();

    }//GEN-LAST:event_btnSimularMouseEntered

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed

//Secção de colecta de dados introduzidos nos inputs
        double capital = Double.parseDouble(tfCapital.getText()), taxaDejuro = Double.parseDouble(tfTaxaJuros.getText());
        int nParcelas = (int) spinnerParcelas.getValue();

        SimuladorEmprestimos simuladorEmprestimos = new SimuladorEmprestimos(taxaDejuro, capital, nParcelas);

        //Declarando ArrayList para receber as parcelas.
        ArrayList<Double> parcelas = new ArrayList<>();
        simuladorEmprestimos.simularEmprestimo();
        lbDivida.setText("Total: " + String.valueOf(simuladorEmprestimos.getDivida()));
        lbCusto.setText(lbCusto.getText() + String.valueOf(simuladorEmprestimos.getJuros()));
        lbParcelas.setText(lbParcelas.getText() + String.valueOf(simuladorEmprestimos.getnParcelas()));
        lbValorParcelas.setText(lbValorParcelas.getText() + String.valueOf(simuladorEmprestimos.getValorParcela()));
        lbJuros.setText(lbJuros.getText() + String.valueOf(simuladorEmprestimos.getJuros()));
        lbTaxaJuros.setText(lbTaxaJuros.getText() + String.valueOf(simuladorEmprestimos.getTaxaDeJuros()));
        simuladorEmprestimos.setTitulo(JOptionPane.showInputDialog("Escolha um Título para o Emprestimo!"));
        lbDetalhes.setText("Detalhes: " + simuladorEmprestimos.getTitulo());
        receptaculoEmprestimos = simuladorEmprestimos;
        btnAderir.setEnabled(true);


    }//GEN-LAST:event_btnSimularActionPerformed

    private void btnAderirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAderirActionPerformed
        
        try {
            EmprestimoDAO.guardar(receptaculoEmprestimos);
        } catch (SQLException ex) {
            Logger.getLogger(PainelEmuladorDeEmprestimos.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnAderirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAderir;
    private javax.swing.JButton btnSimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCusto;
    private javax.swing.JLabel lbDetalhes;
    private javax.swing.JLabel lbDivida;
    private javax.swing.JLabel lbJuros;
    private javax.swing.JLabel lbParcelas;
    private javax.swing.JLabel lbTaxaJuros;
    private javax.swing.JLabel lbValorParcelas;
    private javax.swing.JSpinner spinnerParcelas;
    private javax.swing.JTextField tfCapital;
    private javax.swing.JTextField tfTaxaJuros;
    // End of variables declaration//GEN-END:variables

    //Receptáculo para emprestimo
   public static SimuladorEmprestimos receptaculoEmprestimos = new SimuladorEmprestimos();

    //Metodo usado para validação dos três inputs
    public void validar() {
        if (tfCapital.getText().isBlank()
                || tfTaxaJuros.getText().isBlank()
                || (Integer)spinnerParcelas.getValue()<=0) {
            JOptionPane.showMessageDialog(null, "Por Favor Preencha todos os campos");
        } else if (Double.valueOf(tfCapital.getText())<=0 ||Double.valueOf(tfTaxaJuros.getText())<=0|| (Integer)spinnerParcelas.getValue()<=0)
        {
            JOptionPane.showMessageDialog(null, "Por favor introduza valores maiores que 0 nos campos");
        }
 {}
    }
}
