package view.registro;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import view.perfil.PainelPerfil;

/**
 *
 * @author Grácio Macuácua
 */
public class DadosCadastroP2 extends javax.swing.JPanel implements KeyListener {

    /**
     * Creates new form DadosCadastroP2
     */
    public DadosCadastroP2() {
        initComponents();
        txtProfissao.addKeyListener(this);
        txtEmail.addKeyListener(this);
        pfSenha.addKeyListener(this);
        
        //Coloca a foto padrão como da fotografia de perfil no início do painel
        ImageIcon imgi = new ImageIcon(getClass().getResource("/icones/profile_picture.png"));
        imgi.setImage(imgi.getImage().getScaledInstance(70, 72, 1));
        lblImagem.setIcon(imgi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfissao = new javax.swing.JLabel();
        txtProfissao = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        lblAlterar = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        lblImagem = new view.geral.Circulo();

        setBackground(new java.awt.Color(255, 255, 255));

        lblProfissao.setBackground(new java.awt.Color(255, 255, 255));
        lblProfissao.setForeground(new java.awt.Color(0, 102, 102));
        lblProfissao.setText("Profissão");

        txtProfissao.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtProfissao.setForeground(new java.awt.Color(102, 102, 102));
        txtProfissao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setForeground(new java.awt.Color(0, 102, 102));
        lblEmail.setText("E-mail");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setText("ex: pessoa@teste.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        txtEmail.setPreferredSize(new java.awt.Dimension(131, 22));
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });

        lblFoto.setForeground(new java.awt.Color(0, 102, 102));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Fotografia de perfil");

        lblAlterar.setForeground(new java.awt.Color(0, 102, 102));
        lblAlterar.setText("Alterar");
        lblAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAlterar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAlterarMouseMoved(evt);
            }
        });
        lblAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlterarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlterarMouseExited(evt);
            }
        });

        lblSenha.setBackground(new java.awt.Color(255, 255, 255));
        lblSenha.setForeground(new java.awt.Color(0, 102, 102));
        lblSenha.setText("Senha");

        pfSenha.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pfSenha.setForeground(new java.awt.Color(102, 102, 102));
        pfSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        pfSenha.setPreferredSize(new java.awt.Dimension(76, 22));
        pfSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfSenhaMouseClicked(evt);
            }
        });

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setCorDoCirculo(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblAlterarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseMoved
        lblAlterar.setForeground(new Color(0,153,255));        
    }//GEN-LAST:event_lblAlterarMouseMoved

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        if(evt.getClickCount() == 2)
            txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseClicked

    private void lblAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseExited
        lblAlterar.setForeground(new Color(0,102,102));
    }//GEN-LAST:event_lblAlterarMouseExited

    private void pfSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfSenhaMouseClicked
        if(evt.getClickCount() == 2)
            pfSenha.setText("");
    }//GEN-LAST:event_pfSenhaMouseClicked

    private void lblAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseClicked
        alterarImagem();
    }//GEN-LAST:event_lblAlterarMouseClicked
    
    /**
     * Permite que o utilizador escolha uma fotografia
     * de sua preferência como fotografia de perfil
     */
    private void alterarImagem() {
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i == 0) {
            File arquivo = file.getSelectedFile();
            try {
                BufferedImage imagenInicial = ImageIO.read(arquivo);
                BufferedImage imagemFinal = PainelPerfil.arredondar(imagenInicial);
                PainelRegistro.user.setFotoPerfil(arquivo.getPath());
                lblImagem.setIcon(new ImageIcon(imagemFinal.getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), 1)));
            } catch (IOException ex) {
                Logger.getLogger(DadosCadastroP2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public boolean efectuarValidacao() {
        if(!txtProfissao.getText().isEmpty())
            if(!txtEmail.getText().isEmpty())
                if(txtEmail.getText().contains("@"))
                    if(!pfSenha.getText().isEmpty()) {
                        PainelRegistro.user.setProfissao(txtProfissao.getText());
                        PainelRegistro.user.setEmail(txtEmail.getText());
                        PainelRegistro.user.setSenha(pfSenha.getText());
                        
                        return true;
                    } else
                         System.out.println("Por favor, introduza a sua senha!");
                else
                    System.out.println("E-mail inválido.\nPor favor, introduza um e-mail válido!");
            else
                System.out.println("Por favor, introduza o seu e-mail!");
        else
            System.out.println("Por favor, introduza a sua profissão!");
        
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAlterar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFoto;
    private view.geral.Circulo lblImagem;
    private javax.swing.JLabel lblProfissao;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtProfissao;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {       
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if(e.getKeyCode() == KeyEvent.VK_ENTER) {
            if(txtProfissao.hasFocus()){
                txtEmail.requestFocus();
                txtEmail.setText("");
            } else if(txtEmail.hasFocus()){
                pfSenha.requestFocus();
                pfSenha.setText("");
            } else if(pfSenha.hasFocus()){
                PainelRegistro.btn.requestFocus();
                PainelRegistro.btn.doClick();
            }
        }
    }
}
