package view.registro;

import Dao.UtilizadorDAO;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JButton;
import model.Utilizador;
import view.Main;
import view.geral.Notificacao;
import view.menu.MenuView;


/**
 *
 * @author Grácio Macuácua
 */
public class PainelRegistro extends javax.swing.JPanel implements KeyListener{

    /**
     * Creates new form PainelRegistro2
     */
    public PainelRegistro() {
        initComponents();
        btnProsseguir.addKeyListener(this);
        btn = btnProsseguir;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorPanel1 = new view.geral.ColorPanel();
        lblSistema = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        painelLateral = new javax.swing.JPanel();
        lblCadastre = new javax.swing.JLabel();
        btnProsseguir = new com.k33ptoo.components.KButton();
        container = new javax.swing.JPanel();
        dadosCadastroP1 = new view.registro.DadosCadastroP1();
        dadosCadastroP2 = new view.registro.DadosCadastroP2();
        lblMinimizar = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        colorPanel1.setkEndColor(new java.awt.Color(0, 153, 255));
        colorPanel1.setkStartColor(new java.awt.Color(0, 102, 255));

        lblSistema.setBackground(new java.awt.Color(255, 255, 255));
        lblSistema.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSistema.setForeground(new java.awt.Color(255, 255, 255));
        lblSistema.setText("<html>Sistema de <br> Gestão Financeira</html>");

        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("O PROGRAMA AMIGO PARA GESTÃO IDEAL DAS SUAS FINANÇAS");

        lblLogo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(204, 204, 204));
        lblLogo.setText("LOGOTIPO");

        painelLateral.setBackground(new java.awt.Color(255, 255, 255));

        lblCadastre.setBackground(new java.awt.Color(255, 255, 255));
        lblCadastre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCadastre.setForeground(new java.awt.Color(0, 102, 102));
        lblCadastre.setText("CADASTRE-SE");

        btnProsseguir.setBorder(null);
        btnProsseguir.setText("PROSSEGUIR");
        btnProsseguir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProsseguir.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnProsseguir.setkBorderRadius(0);
        btnProsseguir.setkEndColor(new java.awt.Color(0, 102, 255));
        btnProsseguir.setkHoverColor(new java.awt.Color(12, 91, 160));
        btnProsseguir.setkHoverEndColor(new java.awt.Color(12, 91, 160));
        btnProsseguir.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnProsseguir.setkHoverStartColor(new java.awt.Color(12, 91, 160));
        btnProsseguir.setkPressedColor(new java.awt.Color(0, 102, 255));
        btnProsseguir.setkSelectedColor(new java.awt.Color(255, 255, 255));
        btnProsseguir.setkStartColor(new java.awt.Color(12, 91, 160));
        btnProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsseguirActionPerformed(evt);
            }
        });

        container.setOpaque(false);
        container.setLayout(new java.awt.CardLayout());
        container.add(dadosCadastroP1, "card3");
        container.add(dadosCadastroP2, "card3");

        javax.swing.GroupLayout painelLateralLayout = new javax.swing.GroupLayout(painelLateral);
        painelLateral.setLayout(painelLateralLayout);
        painelLateralLayout.setHorizontalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLateralLayout.createSequentialGroup()
                .addGroup(painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLateralLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblCadastre))
                    .addGroup(painelLateralLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProsseguir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        painelLateralLayout.setVerticalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProsseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        lblMinimizar.setBackground(new java.awt.Color(153, 153, 153));
        lblMinimizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(153, 153, 153));
        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/minimizar.png"))); // NOI18N
        lblMinimizar.setToolTipText("Minimizar");
        lblMinimizar.setIconTextGap(0);
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblExit.setBackground(new java.awt.Color(153, 153, 153));
        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblExit.setForeground(new java.awt.Color(153, 153, 153));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar.png"))); // NOI18N
        lblExit.setToolTipText("Fechar");
        lblExit.setDoubleBuffered(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorPanel1Layout = new javax.swing.GroupLayout(colorPanel1);
        colorPanel1.setLayout(colorPanel1Layout);
        colorPanel1Layout.setHorizontalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(painelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        colorPanel1Layout.setVerticalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanel1Layout.createSequentialGroup()
                .addGroup(colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMinimizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(colorPanel1Layout.createSequentialGroup()
                        .addComponent(lblSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsseguirActionPerformed
        if(dadosCadastroP1.isShowing()){
            if(dadosCadastroP1.efectuarValidacao()) {
                container.removeAll();
                container.repaint();
                container.revalidate();
                container.add(dadosCadastroP2);                
                btnProsseguir.setText("REGISTAR");
            }
        }else if(dadosCadastroP2.efectuarValidacao()) {
            UtilizadorDAO dao = new UtilizadorDAO();
            //if(dao.criar(user)) {
                Notificacao.mostrarDialogoDeOpcaoSingular(Main.main, "Utilizador cadastrado com sucesso!", Notificacao.ICONE_SUCESSO);
                MenuView.user = user;
                Main.exibirPainel(new MenuView());
            //}                            
        }
    }//GEN-LAST:event_btnProsseguirActionPerformed

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        Main.main.setState(Main.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnProsseguir;
    private view.geral.ColorPanel colorPanel1;
    private javax.swing.JPanel container;
    private view.registro.DadosCadastroP1 dadosCadastroP1;
    private view.registro.DadosCadastroP2 dadosCadastroP2;
    private javax.swing.JLabel lblCadastre;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JPanel painelLateral;
    // End of variables declaration//GEN-END:variables
    public static JButton btn;
    public static Utilizador user = new Utilizador();
    
    @Override
    public void keyTyped(KeyEvent e) {        
    }

    @Override
    public void keyPressed(KeyEvent e) {       
    }

    @Override
    public void keyReleased(KeyEvent e) {         
    }
}
