package view;

import com.k33ptoo.utils.ComponentMoverUtil;
import com.k33ptoo.utils.ComponentResizerUtil;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Grácio Macuácua, Bernabé Bila e Paulo Massingue
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        moverFrame(this);
        //redimensionarFrame(this);
    }
   
    
    private void redimensionarFrame(JFrame frame) {
        SwingUtilities.invokeLater(() -> {

        //Para redimensionar o frame
        ComponentResizerUtil cr = new ComponentResizerUtil();
        frame.getRootPane().setBorder(new EmptyBorder(0, 0, 0, 0));
        cr.setSnapSize(new Dimension(5, 5));
        cr.setDragInsets(new Insets(5, 5, 5, 5));
       
        //always register frame to resize
        cr.registerComponent(frame); 

        });
    }
    
    private void moverFrame(JFrame frame) {
        ComponentMoverUtil.moveFrame(frame, false, frame.getComponents());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelControlador = new javax.swing.JPanel();
        painelInicial = new view.PainelInicial();
        painelLogin = new view.ColorPanel();
        painelRegistro = new view.PainelRegistro();
        painelMenu = new view.MenuView();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1186, 621));
        getContentPane().setLayout(new java.awt.CardLayout());

        painelControlador.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        painelControlador.setLayout(new java.awt.CardLayout());
        painelControlador.add(painelInicial, "card6");

        painelLogin.setkEndColor(new java.awt.Color(153, 255, 255));
        painelLogin.setkGradientFocus(100);
        painelLogin.setkStartColor(new java.awt.Color(0, 51, 204));
        painelLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelLoginMouseDragged(evt);
            }
        });
        painelLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                painelLoginKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        painelControlador.add(painelLogin, "card6");
        painelControlador.add(painelRegistro, "card6");
        painelControlador.add(painelMenu, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        painelControlador.add(jPanel1, "card5");

        getContentPane().add(painelControlador, "card4");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_painelLoginKeyPressed
        
    }//GEN-LAST:event_painelLoginKeyPressed

    private void painelLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelLoginMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_painelLoginMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        main = new Main();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main.setVisible(true);
            }
        });
        main.painelInicial.iniciarContagem();
        exibirPainel(main.painelRegistro);
    }
    
    /**
     * Remove todos os painéis da tela de modo a exibir um novo
     * @param add Tela a ser adicionada
     */
    public static void exibirPainel(JPanel add) {
        main.painelControlador.removeAll();
        main.painelControlador.repaint();
        main.painelControlador.revalidate();
        main.painelControlador.add(add);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelControlador;
    private view.PainelInicial painelInicial;
    private view.ColorPanel painelLogin;
    private view.MenuView painelMenu;
    private view.PainelRegistro painelRegistro;
    // End of variables declaration//GEN-END:variables
    public static Main main;
    
}
