/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


/**
 *
 * @author Grácio Macuácua, Bernabé Bila e Paulo Massingue
 */
public class PainelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form PainelRegistro2
     */
    public PainelRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorPanel1 = new view.ColorPanel();
        lblSistema = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        painelLateral = new javax.swing.JPanel();
        txtPNome = new javax.swing.JTextField();
        txtApelido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblPNome = new javax.swing.JLabel();
        lblApelido = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        lblCadastre = new javax.swing.JLabel();
        btnContinuar = new com.k33ptoo.components.KButton();
        lblExit3 = new javax.swing.JLabel();

        colorPanel1.setkEndColor(new java.awt.Color(0, 8, 78));

        lblSistema.setBackground(new java.awt.Color(255, 255, 255));
        lblSistema.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSistema.setForeground(new java.awt.Color(255, 255, 255));
        lblSistema.setText("<html>Sistema de <br> Gestão Financeira</html>");

        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("O PROGRAMA AMIGO PARA GESTÃO IDEAL DAS SUAS FINANÇAS");

        lblLogo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(204, 204, 204));
        lblLogo.setText("LOGOTIPO");

        painelLateral.setBackground(new java.awt.Color(255, 255, 255));

        txtPNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPNome.setForeground(new java.awt.Color(102, 102, 102));
        txtPNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        txtApelido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApelido.setForeground(new java.awt.Color(102, 102, 102));
        txtApelido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        lblPNome.setBackground(new java.awt.Color(255, 255, 255));
        lblPNome.setForeground(new java.awt.Color(0, 102, 102));
        lblPNome.setText("Primeiro Nome");

        lblApelido.setBackground(new java.awt.Color(255, 255, 255));
        lblApelido.setForeground(new java.awt.Color(0, 102, 102));
        lblApelido.setText("Apelido");

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setForeground(new java.awt.Color(0, 102, 102));
        lblEmail.setText("E-mail");

        lblSenha.setBackground(new java.awt.Color(255, 255, 255));
        lblSenha.setForeground(new java.awt.Color(0, 102, 102));
        lblSenha.setText("Senha");

        pfSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfSenha.setForeground(new java.awt.Color(102, 102, 102));
        pfSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        lblCadastre.setBackground(new java.awt.Color(255, 255, 255));
        lblCadastre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCadastre.setForeground(new java.awt.Color(0, 102, 102));
        lblCadastre.setText("CADASTRE-SE");

        btnContinuar.setBorder(null);
        btnContinuar.setText("CONTINUAR");
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnContinuar.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnContinuar.setkBorderRadius(0);
        btnContinuar.setkEndColor(new java.awt.Color(0, 102, 255));
        btnContinuar.setkHoverColor(new java.awt.Color(12, 91, 160));
        btnContinuar.setkHoverEndColor(new java.awt.Color(12, 91, 160));
        btnContinuar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnContinuar.setkHoverStartColor(new java.awt.Color(12, 91, 160));
        btnContinuar.setkPressedColor(new java.awt.Color(0, 102, 255));
        btnContinuar.setkSelectedColor(new java.awt.Color(255, 255, 255));
        btnContinuar.setkStartColor(new java.awt.Color(12, 91, 160));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLateralLayout = new javax.swing.GroupLayout(painelLateral);
        painelLateral.setLayout(painelLateralLayout);
        painelLateralLayout.setHorizontalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLateralLayout.createSequentialGroup()
                .addGroup(painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLateralLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblCadastre))
                    .addGroup(painelLateralLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtApelido)
                            .addComponent(txtPNome)
                            .addComponent(lblPNome)
                            .addComponent(lblApelido)
                            .addComponent(lblEmail)
                            .addComponent(lblSenha)
                            .addComponent(pfSenha)
                            .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        painelLateralLayout.setVerticalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPNome, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblApelido, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        lblExit3.setBackground(new java.awt.Color(153, 153, 153));
        lblExit3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblExit3.setForeground(new java.awt.Color(153, 153, 153));
        lblExit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit3.setText("X");
        lblExit3.setToolTipText("Fechar");
        lblExit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorPanel1Layout = new javax.swing.GroupLayout(colorPanel1);
        colorPanel1.setLayout(colorPanel1Layout);
        colorPanel1Layout.setHorizontalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(lblSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(painelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(colorPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblExit3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        colorPanel1Layout.setVerticalGroup(
            colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanel1Layout.createSequentialGroup()
                .addComponent(lblExit3)
                .addGap(56, 56, 56)
                .addGroup(colorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(colorPanel1Layout.createSequentialGroup()
                        .addComponent(lblSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(painelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExit3MouseClicked

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        Main.exibirPainel(new MenuView());
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnContinuar;
    private view.ColorPanel colorPanel1;
    private javax.swing.JLabel lblApelido;
    private javax.swing.JLabel lblCadastre;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExit3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JPanel painelLateral;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPNome;
    // End of variables declaration//GEN-END:variables
}
