/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.despesas;

import Banco.Conectar;
import Dao.DespesaDao;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Despesa;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Massingue
 */
public class PainelDespesas extends javax.swing.JPanel {

    /**
     * Creates new form Despeza
     */
    public PainelDespesas() {
        initComponents();   
    }
   
    // metodos 
     //metodo para preencher a tabela
    public void preencherTabela() {
        DespesaDao despesaDao = new DespesaDao ();
        List<Despesa> lista = despesaDao.listar();
        DefaultTableModel modeloTabela = (DefaultTableModel) tbDespesa.getModel();
        modeloTabela.setRowCount(0);
        lista.forEach((p) -> {
        modeloTabela.addRow(new Object[]{p.getId(), p.getTipoDespesa(), p.getCusto(), p.getCategoria()});
        });
        
    }
     public void pesquisar() {
        Connection con =Conectar.getConection();
        String sql = "SELECT * FROM despesa WHERE categoria like?";
        try(
            PreparedStatement smt =con.prepareStatement(sql)){
            smt.setString(1,txtPesquisaDespesa.getText()+"%");
            smt.executeQuery();
            tbDespesa.setModel(DbUtils.resultSetToTableModel(smt.executeQuery()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Ocorreu um erro ao pesquisar!");
        }   
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTipoDespesa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        spCusto = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDespesa = new javax.swing.JTable();
        txtPesquisaDespesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        graficoCircularDespesa = new javax.swing.JPanel();
        grafico1 = new view.despesas.Grafico();
        lblDespesaTotal = new javax.swing.JLabel();
        lblDespesaFixa = new javax.swing.JLabel();
        lblDespesaVariavel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSalvarDespesa = new javax.swing.JButton();
        btnActualizarDespesa = new javax.swing.JButton();
        btnExcluirDespesa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(950, 594));
        setMinimumSize(new java.awt.Dimension(950, 594));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(950, 594));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Tipo");

        cbTipoDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fixa", "Variavel" }));
        cbTipoDespesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbTipoDespesaKeyPressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Custo");

        spCusto.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spCustoKeyPressed(evt);
            }
        });

        tbDespesa.setBackground(new java.awt.Color(255, 255, 255));
        tbDespesa.getTableHeader().setBackground(Color.WHITE);
        tbDespesa.getTableHeader().setForeground(new Color(104,104,104));
        tbDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Custo", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDespesa.setOpaque(false);
        tbDespesa.setRowHeight(30);
        jScrollPane1.setViewportView(tbDespesa);
        tbDespesa.setRowHeight(30);
        if (tbDespesa.getColumnModel().getColumnCount() > 0) {
            tbDespesa.getColumnModel().getColumn(0).setResizable(false);
            tbDespesa.getColumnModel().getColumn(1).setResizable(false);
            tbDespesa.getColumnModel().getColumn(2).setResizable(false);
            tbDespesa.getColumnModel().getColumn(3).setResizable(false);
        }

        txtPesquisaDespesa.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisaDespesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisaDespesa.setText("Pesquisar despesas");
        txtPesquisaDespesa.setToolTipText("Pesquisar");
        txtPesquisaDespesa.setBorder(null);
        txtPesquisaDespesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtPesquisaDespesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaDespesaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaDespesaFocusLost(evt);
            }
        });
        txtPesquisaDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaDespesaActionPerformed(evt);
            }
        });
        txtPesquisaDespesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaDespesaKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Total:");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Despesa Fixa");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Despesa Variável");

        graficoCircularDespesa.setOpaque(false);

        javax.swing.GroupLayout grafico1Layout = new javax.swing.GroupLayout(grafico1);
        grafico1.setLayout(grafico1Layout);
        grafico1Layout.setHorizontalGroup(
            grafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grafico1Layout.setVerticalGroup(
            grafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graficoCircularDespesaLayout = new javax.swing.GroupLayout(graficoCircularDespesa);
        graficoCircularDespesa.setLayout(graficoCircularDespesaLayout);
        graficoCircularDespesaLayout.setHorizontalGroup(
            graficoCircularDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grafico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        graficoCircularDespesaLayout.setVerticalGroup(
            graficoCircularDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grafico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblDespesaTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDespesaTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblDespesaTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDespesaTotal.setText("0.0");

        lblDespesaFixa.setForeground(new java.awt.Color(102, 102, 102));
        lblDespesaFixa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDespesaFixa.setText("0.0");

        lblDespesaVariavel.setForeground(new java.awt.Color(102, 102, 102));
        lblDespesaVariavel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDespesaVariavel.setText("0.0");

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 100, 0));

        btnSalvarDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adicionar-botao.png"))); // NOI18N
        btnSalvarDespesa.setContentAreaFilled(false);
        btnSalvarDespesa.setMaximumSize(new java.awt.Dimension(30, 40));
        btnSalvarDespesa.setPreferredSize(new java.awt.Dimension(30, 40));
        btnSalvarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDespesaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalvarDespesa);

        btnActualizarDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar-pares-de-setas-em-circulo.png"))); // NOI18N
        btnActualizarDespesa.setContentAreaFilled(false);
        btnActualizarDespesa.setMaximumSize(new java.awt.Dimension(30, 40));
        btnActualizarDespesa.setPreferredSize(new java.awt.Dimension(30, 40));
        btnActualizarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDespesaActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizarDespesa);

        btnExcluirDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        btnExcluirDespesa.setContentAreaFilled(false);
        btnExcluirDespesa.setMaximumSize(new java.awt.Dimension(30, 40));
        btnExcluirDespesa.setPreferredSize(new java.awt.Dimension(30, 40));
        btnExcluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDespesaActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluirDespesa);

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Categoria");

        txtCategoria.setBackground(new java.awt.Color(255, 255, 255));
        txtCategoria.setForeground(new java.awt.Color(51, 51, 51));
        txtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCategoriaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spCusto)
                                .addGap(88, 88, 88)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(260, 260, 260))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtPesquisaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDespesaFixa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDespesaVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDespesaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(graficoCircularDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPesquisaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDespesaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDespesaFixa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDespesaVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graficoCircularDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDespesaActionPerformed
        Despesa p = new Despesa();
        p.setTipoDespesa((String) cbTipoDespesa.getSelectedItem());
        p.setCusto(Double.parseDouble(spCusto.getValue().toString()));
        p.setCategoria(txtCategoria.getText());
        DespesaDao DespesaDao = new  DespesaDao();
        DespesaDao.cadastrar(p);
        preencherTabela();
    }//GEN-LAST:event_btnSalvarDespesaActionPerformed

    private void btnActualizarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDespesaActionPerformed
        Despesa p = new Despesa();
        p.setTipoDespesa((String) cbTipoDespesa.getSelectedItem());
        p.setCusto((double) spCusto.getValue());
        p.setCategoria(txtCategoria.getText());
        DespesaDao despesaDao = new DespesaDao();
        despesaDao.actualizar(p);
        preencherTabela();

    }//GEN-LAST:event_btnActualizarDespesaActionPerformed

    private void btnExcluirDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDespesaActionPerformed
            int opcao = tbDespesa.getSelectedRow();
        if (opcao >= 0) {
            Despesa p = new Despesa();
            p.setId(Integer.parseInt(tbDespesa.getValueAt(opcao, 0).toString()));
            p.setTipoDespesa(tbDespesa.getValueAt(opcao, 1).toString());
            p.setCusto(Double.parseDouble(tbDespesa.getValueAt(opcao, 2).toString()));
            p.setCategoria(tbDespesa.getValueAt(opcao, 3).toString());
            DespesaDao DespesaDao = new DespesaDao();
            DespesaDao.excluir(p);
            preencherTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }

    }//GEN-LAST:event_btnExcluirDespesaActionPerformed

    private void txtPesquisaDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaDespesaActionPerformed
    pesquisar();
    }//GEN-LAST:event_txtPesquisaDespesaActionPerformed

    private void txtPesquisaDespesaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaDespesaKeyReleased
         pesquisar();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaDespesaKeyReleased

    private void txtPesquisaDespesaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaDespesaFocusGained
          if(txtPesquisaDespesa.getText().equals("")){
            txtPesquisaDespesa.setText("Pesquisar despesas");
            txtPesquisaDespesa.setForeground(new Color(152,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaDespesaFocusGained

    private void txtPesquisaDespesaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaDespesaFocusLost
          if(txtPesquisaDespesa.getText().equals("Pesquisar despesas")){
            txtPesquisaDespesa.setText("");
            txtPesquisaDespesa.setForeground(new Color(152,153,153));
        }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaDespesaFocusLost

    private void cbTipoDespesaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTipoDespesaKeyPressed
           if(evt.getKeyCode() == KeyEvent.VK_ENTER)
              spCusto.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDespesaKeyPressed

    private void spCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spCustoKeyPressed
          if(evt.getKeyCode() == KeyEvent.VK_ENTER)
              txtCategoria.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_spCustoKeyPressed

    private void txtCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaKeyPressed
             if(evt.getKeyCode() == KeyEvent.VK_ENTER)
             btnSalvarDespesa.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaKeyPressed

     //metodo que permite inserir os valores nos rendimentos total,fixo,variavel
    Double fixaDespesa;
    Double variavelDespesa;
    Double SomaDespesa;
    public void inserirValores(){
        Despesa p = new Despesa();  
        if(p.getTipoDespesa().equals("Fixa")){
            JLabel lblDespesaFixa = new JLabel((String) spCusto.getValue());
            fixaDespesa= (Double) spCusto.getValue();
        }else if(p.getTipoDespesa().equals("Variavel")){
            JLabel lblDespesaVariavel = new JLabel((String) spCusto.getValue()); 
            variavelDespesa = (Double) spCusto.getValue(); 
        }else{
            SomaDespesa = fixaDespesa+variavelDespesa;
            JLabel lblRendimentoTotal = new JLabel(Double.toString(SomaDespesa)); 
        }   
  }  
  
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDespesa;
    private javax.swing.JButton btnExcluirDespesa;
    private javax.swing.JButton btnSalvarDespesa;
    private javax.swing.JComboBox<String> cbTipoDespesa;
    private view.despesas.Grafico grafico1;
    private javax.swing.JPanel graficoCircularDespesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDespesaFixa;
    private javax.swing.JLabel lblDespesaTotal;
    private javax.swing.JLabel lblDespesaVariavel;
    private javax.swing.JSpinner spCusto;
    private javax.swing.JTable tbDespesa;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtPesquisaDespesa;
    // End of variables declaration//GEN-END:variables
}
