package view.declaracaoderendimentos;

import Banco.Conectar;
import Dao.RendimentoDao;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.List;
<<<<<<< Updated upstream
<<<<<<< Updated upstream
import javax.swing.*;
=======
import javax.swing.JLabel;
>>>>>>> Stashed changes
=======
import javax.swing.JLabel;
>>>>>>> Stashed changes
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Rendimento;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Grácio Macuácua
 */
public class PainelDeclaracaoRendimentos extends javax.swing.JPanel {

    /**
     * Creates new form PainelDeclaracaoRendimentos
     */
    public PainelDeclaracaoRendimentos() {
        initComponents();
        preencherTabela();
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        inserirValores();
=======
        metodoRendimentos();
>>>>>>> Stashed changes
=======
        metodoRendimentos();
>>>>>>> Stashed changes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spRendimentos = new javax.swing.JSpinner();
        cbTipoRendimento = new javax.swing.JComboBox<>();
        cbPeridoRendimento = new javax.swing.JComboBox<>();
        txtPesquisaRendimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnPesquisaRendimento = new javax.swing.JButton();
        txtFonte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRendimentoFixo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblRendimentoVariavel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblRendimentoTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaRendimento = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnSalvarRendimento = new javax.swing.JButton();
        btnActualizarRendimento = new javax.swing.JButton();
        btnExcluirRendimento = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(950, 594));
        setMinimumSize(new java.awt.Dimension(950, 594));
        setPreferredSize(new java.awt.Dimension(950, 594));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Declaracao de rendimento"));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Rendimento");

        spRendimentos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spRendimentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spRendimentosKeyPressed(evt);
            }
        });

        cbTipoRendimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fixo", " Variavel" }));
        cbTipoRendimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbTipoRendimentoKeyPressed(evt);
            }
        });

        cbPeridoRendimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diario", "Semanal", "Mensal", " ", " " }));
        cbPeridoRendimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbPeridoRendimentoKeyPressed(evt);
            }
        });

        txtPesquisaRendimento.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisaRendimento.setText("Pesquisar Rendimento");
        txtPesquisaRendimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaRendimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaRendimentoFocusLost(evt);
            }
        });
        txtPesquisaRendimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaRendimentoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Fonte de Rendimento:");

        btnPesquisaRendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N

        txtFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFonteActionPerformed(evt);
            }
        });
        txtFonte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFonteKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Tipo");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Periodo");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Rendimento Fixo");

        lblRendimentoFixo.setForeground(new java.awt.Color(102, 102, 102));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Rendimento Variavel");

        lblRendimentoVariavel.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Total");

        lblRendimentoTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRendimentoTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblRendimentoTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(cbTipoRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(spRendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(txtFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbPeridoRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtPesquisaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btnPesquisaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblRendimentoFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRendimentoVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblRendimentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(cbTipoRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(spRendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(cbPeridoRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtPesquisaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnPesquisaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblRendimentoFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblRendimentoVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRendimentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tabelaRendimento.getTableHeader().setBackground(Color.WHITE);
        tabelaRendimento.getTableHeader().setForeground(new Color(104,104,104));
        tabelaRendimento.setRowHeight(30);
        tabelaRendimento.setBackground(new java.awt.Color(255, 255, 255));
        tabelaRendimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Rendimento", "Periodo", "Fonte"
            }
        ));
        jScrollPane2.setViewportView(tabelaRendimento);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 100, 0));

        btnSalvarRendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adicionar-botao.png"))); // NOI18N
        btnSalvarRendimento.setMaximumSize(new java.awt.Dimension(30, 40));
        btnSalvarRendimento.setPreferredSize(new java.awt.Dimension(30, 40));
        btnSalvarRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarRendimentoActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalvarRendimento);

        btnActualizarRendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar-pares-de-setas-em-circulo.png"))); // NOI18N
        btnActualizarRendimento.setMaximumSize(new java.awt.Dimension(30, 40));
        btnActualizarRendimento.setPreferredSize(new java.awt.Dimension(30, 40));
        btnActualizarRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarRendimentoActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizarRendimento);

        btnExcluirRendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        btnExcluirRendimento.setMaximumSize(new java.awt.Dimension(30, 40));
        btnExcluirRendimento.setPreferredSize(new java.awt.Dimension(30, 40));
        btnExcluirRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirRendimentoActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluirRendimento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarRendimentoActionPerformed
        /*DefaultTableModel modeloTabela = (DefaultTableModel) tabelaRendimento.getModel();
        Object dados[] = {cbTipoRendimento.getSelectedItem(),spRendimentos.getValue(),cbPeridoRendimento.getSelectedItem(),txtFonte.getText()};
        modeloTabela.addRow(dados);*/
        Rendimento p = new Rendimento();
        p.setTipoRendimento((String) cbTipoRendimento.getSelectedItem());
        p.setRendimento((double) spRendimentos.getValue());
        p.setPeriodo((String) cbPeridoRendimento.getSelectedItem());
        p.setFonteRendimento(txtFonte.getText());
        RendimentoDao rendeDao = new  RendimentoDao();
        rendeDao.cadastrar(p);
        preencherTabela();
    }//GEN-LAST:event_btnSalvarRendimentoActionPerformed

    private void btnExcluirRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirRendimentoActionPerformed
//metodo para excluir dados numa tabela 
        int opcao = tabelaRendimento.getSelectedRow();
        if (opcao >= 0) {
            Rendimento p = new Rendimento();
            p.setId(Integer.parseInt(tabelaRendimento.getValueAt(opcao, 0).toString()));
            p.setTipoRendimento(tabelaRendimento.getValueAt(opcao, 1).toString());
            p.setRendimento(Double.parseDouble(tabelaRendimento.getValueAt(opcao, 2).toString()));
            p.setPeriodo(tabelaRendimento.getValueAt(opcao, 3).toString());
            p.setFonteRendimento(tabelaRendimento.getValueAt(opcao, 4).toString());
            RendimentoDao rendeDao = new RendimentoDao();
            rendeDao.excluir(p);
            preencherTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirRendimentoActionPerformed

    private void btnActualizarRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarRendimentoActionPerformed
 //metodo para actualizar
        Rendimento p = new Rendimento();
        p.setTipoRendimento((String) cbTipoRendimento.getSelectedItem());
        p.setRendimento((double) spRendimentos.getValue());
        p.setPeriodo((String)cbPeridoRendimento.getSelectedItem());
        p.setFonteRendimento(txtFonte.getText());
        RendimentoDao rendeDao = new RendimentoDao();
        rendeDao.actualizar(p);
        preencherTabela();

    }//GEN-LAST:event_btnActualizarRendimentoActionPerformed

    private void txtPesquisaRendimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaRendimentoKeyReleased
//aplicar metodo de pesquisa 
pesquisar();
    }//GEN-LAST:event_txtPesquisaRendimentoKeyReleased

    private void txtPesquisaRendimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaRendimentoFocusGained
    // permite focar e desfocar txt de pesquisa
     if(txtPesquisaRendimento.getText().equals("")){
     txtPesquisaRendimento.setText("Pesquisar Rendimento");
     txtPesquisaRendimento.setForeground(new Color(152,153,153));
}
        
    }//GEN-LAST:event_txtPesquisaRendimentoFocusGained

    private void txtPesquisaRendimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaRendimentoFocusLost
     //desfoque na pesquisa
        if(txtPesquisaRendimento.getText().equals("Pesquisar Rendimento")){
     txtPesquisaRendimento.setText("");
     txtPesquisaRendimento.setForeground(new Color(152,153,153));
}
        
    }//GEN-LAST:event_txtPesquisaRendimentoFocusLost

    private void cbTipoRendimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTipoRendimentoKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    spRendimentos.requestFocus();
}
    }//GEN-LAST:event_cbTipoRendimentoKeyPressed

    private void spRendimentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spRendimentosKeyPressed

    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    cbPeridoRendimento.requestFocus();
    }//GEN-LAST:event_spRendimentosKeyPressed
    }
    private void cbPeridoRendimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbPeridoRendimentoKeyPressed
       // foco
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    txtFonte.requestFocus(); 
     }
    }//GEN-LAST:event_cbPeridoRendimentoKeyPressed

    private void txtFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFonteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFonteActionPerformed

    private void txtFonteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFonteKeyPressed
     // foco para botao gravar
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        btnSalvarRendimento.requestFocus(); 
     }
    
    }//GEN-LAST:event_txtFonteKeyPressed
<<<<<<< Updated upstream
<<<<<<< Updated upstream
     
//metodo que permite inserir os valores nos rendimentos total,fixo,variavel
    Double fixoRendimento;
    Double variavelRendimento;
    Double SomaRendimento;
  public void inserirValores(){
    Rendimento p=new Rendimento();  
   if(p.tipoRendimento.equals("Fixo")){
     JLabel lblRendimentoFixo=new JLabel((String) spRendimentos.getValue());
     fixoRendimento= (Double) spRendimentos.getValue();
   }else if(p.tipoRendimento.equals("Variavel")){
     JLabel lblRendimentoVariavel=new JLabel((String) spRendimentos.getValue()); 
      variavelRendimento =(Double) spRendimentos.getValue(); 
   }else{
    SomaRendimento=fixoRendimento+variavelRendimento;
    JLabel lblRendimentoTotal=new JLabel(Double.toString(SomaRendimento)); 
   }   
  }  
=======
=======
>>>>>>> Stashed changes
   // metodo pra inserir valores de rendimento variavel fixo, total
    Double fixoRendimento;
    Double variavelRendimento;
    Double somaRendimento;
<<<<<<< Updated upstream
=======
    
   public void metodoRendimentos(){
   Rendimento p =new Rendimento();
   if(p.getTipoRendimento().equals("Fixo")){
      JLabel  lblRendimentoFixo=new JLabel((String) spRendimentos.getValue());
      fixoRendimento=(Double) spRendimentos.getValue();
   }else if(p.getTipoRendimento().equals("Variavel")){
      JLabel  lblRendimentoVariavel=new JLabel((String) spRendimentos.getValue());
      variavelRendimento=(Double) spRendimentos.getValue();
   }else{
     somaRendimento= fixoRendimento+variavelRendimento; 
   JLabel  lblRendimentoTotal=new JLabel(Double.toString(somaRendimento));
   }
}
>>>>>>> Stashed changes
    
   public void metodoRendimentos(){
   Rendimento p =new Rendimento();
   if(p.getTipoRendimento().equals("Fixo")){
      JLabel  lblRendimentoFixo=new JLabel((String) spRendimentos.getValue());
      fixoRendimento=(Double) spRendimentos.getValue();
   }else if(p.getTipoRendimento().equals("Variavel")){
      JLabel  lblRendimentoVariavel=new JLabel((String) spRendimentos.getValue());
      variavelRendimento=(Double) spRendimentos.getValue();
   }else{
     somaRendimento= fixoRendimento+variavelRendimento; 
   JLabel  lblRendimentoTotal=new JLabel(Double.toString(somaRendimento));
   }
}
    
>>>>>>> Stashed changes
    //metodo para preencher a tabela
    public void preencherTabela() {
        // metodo para preencher a tabela 
        RendimentoDao rendeDao= new RendimentoDao ();
        List<Rendimento> lista = rendeDao.listar();
        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaRendimento.getModel();
        modeloTabela.setRowCount(0);
        lista.forEach((p) -> {
            modeloTabela.addRow(new Object[]{cbTipoRendimento.getSelectedItem(),spRendimentos.getValue(),cbPeridoRendimento.getSelectedItem(),txtFonte.getText()});
        });
        
    }
    //metodo para pesquisar
     public void pesquisar() {
        //metodo que perimte pesquisar dados 
        Connection con =Conectar.getConection();
        String sql = "SELECT * FROM rendimento WHERE nome like?";
        try(PreparedStatement smt =con.prepareStatement(sql)){
          smt.setString(1,txtPesquisaRendimento.getText()+"%");
          smt.executeQuery();
          tabelaRendimento.setModel(DbUtils.resultSetToTableModel(smt.executeQuery()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Ocorreu um erro!");
        }
   
    
  
        
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarRendimento;
    private javax.swing.JButton btnExcluirRendimento;
    private javax.swing.JButton btnPesquisaRendimento;
    private javax.swing.JButton btnSalvarRendimento;
    private javax.swing.JComboBox<String> cbPeridoRendimento;
    private javax.swing.JComboBox<String> cbTipoRendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRendimentoFixo;
    private javax.swing.JLabel lblRendimentoTotal;
    private javax.swing.JLabel lblRendimentoVariavel;
    private javax.swing.JSpinner spRendimentos;
    private javax.swing.JTable tabelaRendimento;
    private javax.swing.JTextField txtFonte;
    private javax.swing.JTextField txtPesquisaRendimento;
    // End of variables declaration//GEN-END:variables
}
