package view.estatisticas;

import java.awt.Color;
import java.awt.Graphics;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *Classe que faz o desenho do gráfico da tela de estatísticas
 * @author Grácio Macuácua
 */
public final class Grafico extends javax.swing.JPanel {

    public double emergencias;
    public double muitoImportante;
    public double importante;
    public double lazer;
    public double opcional;
            
    /**
     * Creates new form Grafico
     */
    public Grafico() {
        initComponents();        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(emergencias, "", "Emergência");
        dataset.setValue(muitoImportante, "", "Muito Importante");
        dataset.setValue(importante, "", "Importante");
        dataset.setValue(lazer, "", "Lazer");
        dataset.setValue(opcional, "", "Opcional");
        
        JFreeChart chart = ChartFactory.createBarChart("Estatísticas de uso das finanças", "Prioridade", "Impacto sobre os gastos",
                dataset, PlotOrientation.VERTICAL, false, true, false);
        chart.getTitle().setPaint(new Color(153,153,153));
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        categoryPlot.setRangeGridlinePaint(Color.BLUE);
        categoryPlot.setBackgroundPaint(Color.LIGHT_GRAY);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(255,51,51);
        renderer.setSeriesPaint(0, clr3);

        ChartPanel barpChartPanel = new ChartPanel(chart);
        barpChartPanel.setSize(getWidth(), getHeight());
        
        add(barpChartPanel);         
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
