package view.entrada;

import view.registro.PainelRegistro;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import view.Main;
import view.menu.MenuView;

/**
 *
 * @author Grácio Macuácua
 */
public class PainelEntrada extends javax.swing.JPanel implements KeyListener {

    /**
     * Creates new form PainelLogin
     */
    public PainelEntrada() {
        initComponents();
        txtUsuario.addKeyListener(this);
        pfSenha.addKeyListener(this);
        btnEntrar.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBackground1 = new view.entrada.LoginBackground();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistar = new com.k33ptoo.components.KButton();
        btnEntrar = new com.k33ptoo.components.KButton();
        lblEsqueciSenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        lblIcone = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        loginBackground1.setMinimumSize(new java.awt.Dimension(1180, 621));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("nome de usuário");
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("ou");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Faça login para continuar");

        btnRegistar.setText("REGISTAR-ME");
        btnRegistar.setContentAreaFilled(false);
        btnRegistar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistar.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnRegistar.setkEndColor(new java.awt.Color(0, 102, 255));
        btnRegistar.setkHoverColor(new java.awt.Color(12, 90, 160));
        btnRegistar.setkHoverEndColor(new java.awt.Color(12, 91, 160));
        btnRegistar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnRegistar.setkHoverStartColor(new java.awt.Color(12, 91, 160));
        btnRegistar.setkPressedColor(new java.awt.Color(0, 102, 255));
        btnRegistar.setkSelectedColor(new java.awt.Color(255, 255, 255));
        btnRegistar.setkStartColor(new java.awt.Color(12, 91, 160));
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        btnEntrar.setText("ENTRAR");
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrar.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnEntrar.setkEndColor(new java.awt.Color(0, 102, 255));
        btnEntrar.setkHoverColor(new java.awt.Color(12, 90, 160));
        btnEntrar.setkHoverEndColor(new java.awt.Color(12, 91, 160));
        btnEntrar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnEntrar.setkHoverStartColor(new java.awt.Color(12, 91, 160));
        btnEntrar.setkPressedColor(new java.awt.Color(0, 102, 255));
        btnEntrar.setkSelectedColor(new java.awt.Color(255, 255, 255));
        btnEntrar.setkStartColor(new java.awt.Color(12, 91, 160));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblEsqueciSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEsqueciSenha.setForeground(new java.awt.Color(0, 102, 255));
        lblEsqueciSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEsqueciSenha.setText("Esqueci a senha");
        lblEsqueciSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEsqueciSenha.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblEsqueciSenhaMouseMoved(evt);
            }
        });
        lblEsqueciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqueciSenhaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEsqueciSenhaMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/visivel.png"))); // NOI18N
        jLabel1.setToolTipText("Mostrar senha");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        pfSenha.setBackground(new java.awt.Color(255, 255, 255));
        pfSenha.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pfSenha.setForeground(new java.awt.Color(102, 102, 102));
        pfSenha.setText("suassenha");
        pfSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        pfSenha.setPreferredSize(new java.awt.Dimension(76, 22));
        pfSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfSenhaMouseClicked(evt);
            }
        });

        lblIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_user_120px.png"))); // NOI18N

        lblMinimizar.setBackground(new java.awt.Color(153, 153, 153));
        lblMinimizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(153, 153, 153));
        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/minimizar.png"))); // NOI18N
        lblMinimizar.setToolTipText("Minimizar");
        lblMinimizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMinimizar.setIconTextGap(0);
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblExit.setBackground(new java.awt.Color(153, 153, 153));
        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblExit.setForeground(new java.awt.Color(153, 153, 153));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar.png"))); // NOI18N
        lblExit.setToolTipText("Fechar");
        lblExit.setDoubleBuffered(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginBackground1Layout = new javax.swing.GroupLayout(loginBackground1);
        loginBackground1.setLayout(loginBackground1Layout);
        loginBackground1Layout.setHorizontalGroup(
            loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBackground1Layout.createSequentialGroup()
                .addGap(727, 727, 727)
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1))
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEsqueciSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(186, 186, 186))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBackground1Layout.createSequentialGroup()
                        .addComponent(lblIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBackground1Layout.createSequentialGroup()
                        .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        loginBackground1Layout.setVerticalGroup(
            loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBackground1Layout.createSequentialGroup()
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMinimizar))
                .addGap(24, 24, 24)
                .addComponent(lblIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addComponent(btnRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lblEsqueciSenha))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblEsqueciSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueciSenhaMouseExited
        lblEsqueciSenha.setForeground(new Color(0,102,255));
    }//GEN-LAST:event_lblEsqueciSenhaMouseExited

    private void lblEsqueciSenhaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueciSenhaMouseMoved
        lblEsqueciSenha.setForeground(new Color(0,153,255));        
    }//GEN-LAST:event_lblEsqueciSenhaMouseMoved

    private void lblEsqueciSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueciSenhaMouseClicked
        System.out.println("EM DESENVOLVIMENTO");
    }//GEN-LAST:event_lblEsqueciSenhaMouseClicked

    private void pfSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfSenhaMouseClicked
        if(evt.getClickCount() == 2)
        pfSenha.setText("");
    }//GEN-LAST:event_pfSenhaMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        if(jLabel1.getIcon() == new ImageIcon(getClass().getResource("/icones/visivel.png"))) {
            jLabel1.setToolTipText("Mostrar senha");
        } else if(jLabel1.getIcon() == new ImageIcon(getClass().getResource("/icones/invisivel.png")))
            jLabel1.setToolTipText("Ocultar senha");
    }//GEN-LAST:event_jLabel1MouseEntered

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        if(evt.getClickCount() == 2)
            txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(jLabel1.getToolTipText().equalsIgnoreCase("mostrar senha")) {
            pfSenha.setEchoChar((char) 0);
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/icones/invisivel.png")));
            jLabel1.setToolTipText("Ocultar senha");
        } else if(jLabel1.getToolTipText().equalsIgnoreCase("ocultar senha")) {
            pfSenha.setEchoChar('*');
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/icones/visivel.png")));
            jLabel1.setToolTipText("Mostrar senha");
        }           
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        Main.exibirPainel(new PainelRegistro());
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        Main.main.setState(Main.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Main.exibirPainel(new MenuView());
    }//GEN-LAST:event_btnEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnEntrar;
    private com.k33ptoo.components.KButton btnRegistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEsqueciSenha;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblIcone;
    private javax.swing.JLabel lblMinimizar;
    private view.entrada.LoginBackground loginBackground1;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if(e.getKeyCode() == KeyEvent.VK_ENTER) {
            if(txtUsuario.hasFocus()){
                pfSenha.requestFocus();
                pfSenha.setText("");
            } else if(pfSenha.hasFocus()){
                btnEntrar.requestFocus();
                btnEntrar.doClick();
            }
        }
    }
}
